$primary = rgb(4f80fc)
$surface = rgb(03123a)
$secondary = rgb(6136fc)
$error = rgb(fd4663)
$tertiary = rgb(c436fc)
$surface_lowest = rgb(020a1c)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
