$primary = rgb(799ff2)
$surface = rgb(061538)
$secondary = rgb(8f79f2)
$error = rgb(cc7092)
$tertiary = rgb(ce6e91)
$surface_lowest = rgb(030b1c)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
