$primary = rgb(70dba7)
$surface = rgb(111412)
$secondary = rgb(b4ccbc)
$error = rgb(ffb4ab)
$tertiary = rgb(a4cddd)
$surface_lowest = rgb(0c0f0d)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
