[catalog.karere]
name = "Karere Custom CSS"
category = "chat"

[templates.karere]
input_path = "karere.css"
output_path = "$XDG_CONFIG_HOME/karere/custom.css"
requires_path = "$XDG_CONFIG_HOME/karere"
