[catalog.sioyek]
name = "sioyek"
category = "misc"

[templates.sioyek]
input_path = "sioyek.config"
output_path = "$XDG_CONFIG_HOME/sioyek/themes/noctalia.config"
requires_path = "$XDG_CONFIG_HOME/sioyek"
post_hook = "bash '{{ config_dir }}/apply.sh'"
