[catalog.superfile]
name = "superfile"
category = "terminal"

[templates.superfile]
input_path = "superfile.toml"
output_path = "$XDG_CONFIG_HOME/superfile/theme/noctalia.toml"
post_hook = "bash '{{ config_dir }}/apply.sh'"
