[colors.primary]
background = '#101c2e'
foreground = '#f2f2f3'

[colors.cursor]
text = '#101c2e'
cursor = '#f2f2f3'

[colors.vi_mode_cursor]
text = '#101c2e'
cursor = '#679ce4'

[colors.search.matches]
foreground = '#15263d'
background = '#a166cc'

[colors.search.focused_match]
foreground = '#15263d'
background = '#679ce4'

[colors.footer_bar]
foreground = '#15263d'
background = '#e3e5e8'

[colors.hints.start]
foreground = '#15263d'
background = '#655cd6'

[colors.hints.end]
foreground = '#15263d'
background = '#655cd6'

[colors.selection]
text = '#afb2b6'
background = '#15263d'


[colors.normal]
black   = '#15263d'
red     = '#c67088'
green   = '#679ce4'
yellow  = '#655cd6'
blue    = '#a166cc'
magenta = '#93b8ec'
cyan    = '#9c96e9'
white   = '#f2f2f3'


[colors.bright]
black   = '#5f6874'
red     = '#c67088'
green   = '#679ce4'
yellow  = '#655cd6'
blue    = '#a166cc'
magenta = '#93b8ec'
cyan    = '#9c96e9'
white   = '#f2f2f3'


[colors.dim]
black   = '#15263d'
red     = '#c67088'
green   = '#679ce4'
yellow  = '#655cd6'
blue    = '#a166cc'
magenta = '#93b8ec'
cyan    = '#9c96e9'
white   = '#f2f2f3'
