color0 #282828
color1 #fb4934
color2 #29cc52
color3 #ccbe29
color4 #b8bb26
color5 #fabd2f
color6 #83a598
color7 #fbf1c7
color8 #3c3836
color9 #ff614e
color10 #49f273
color11 #f2e449
color12 #dee144
color13 #ffc849
color14 #b6cbc3
color15 #ffffff
background #282828
selection_foreground #282828
cursor #b8bb26
cursor_text_color #282828
foreground #fbf1c7
selection_background #b8bb26
active_border_color #b8bb26
inactive_border_color #fabd2f

active_tab_foreground   #282828
active_tab_background   #b8bb26
inactive_tab_foreground #ebdbb2
inactive_tab_background #3c3836
cursor_trail_color      #ebdbb2
