color0 #061538
color1 #cc7092
color2 #799ff2
color3 #8f79f2
color4 #ce6e91
color5 #8bacf4
color6 #9e8bf4
color7 #f2f2f3
color8 #5d6471
color9 #cc7092
color10 #799ff2
color11 #8f79f2
color12 #ce6e91
color13 #8bacf4
color14 #9e8bf4
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #061538
background            #061538
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #081c49
active_border_color   #799ff2
inactive_border_color #081c49
url_color             #799ff2
