color0 #171f26
color1 #fd4663
color2 #67aae4
color3 #5c60d6
color4 #9566cc
color5 #93c2ec
color6 #9699e9
color7 #f2f2f3
color8 #5f6a73
color9 #fd4663
color10 #67aae4
color11 #5c60d6
color12 #9566cc
color13 #93c2ec
color14 #9699e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #171f26
background            #171f26
foreground            #f2f2f3
selection_foreground  #afb3b6
selection_background  #1f2a33
active_border_color   #67aae4
inactive_border_color #1f2a33
url_color             #67aae4
