color0 #03123a
color1 #fd4663
color2 #4f80fc
color3 #6136fc
color4 #c436fc
color5 #82a5fd
color6 #9c81fd
color7 #f2f2f3
color8 #5d6371
color9 #fd4663
color10 #4f80fc
color11 #6136fc
color12 #c436fc
color13 #82a5fd
color14 #9c81fd
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #03123a
background            #03123a
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #081a49
active_border_color   #4f80fc
inactive_border_color #081a49
url_color             #4f80fc

active_tab_foreground   #181c25
active_tab_background   #4f80fc
inactive_tab_foreground #afb1b6
inactive_tab_background #081a49
cursor_trail_color      #afb1b6
